=== Soothsilver/xmlcheck/www/phptests/plugins/cases/DTD/Veronika Maurerova/data.dtd
<!ENTITY user_details "ud">
<!ENTITY % reference_attrs
"id  ID #REQUIRED" >
<!ELEMENT root-element ((users))>
<!ELEMENT users ((user+))>
<!ELEMENT user ((ud, todo_list))>
<!ATTLIST user
	id ID #REQUIRED
>
<!ELEMENT ud ((login, password_hash, salt, name))>
<!ELEMENT login (#PCDATA)>
<!ELEMENT name ((first_name, last_name))>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT password_hash (#PCDATA)>
<!ELEMENT salt (#PCDATA)>
<!ELEMENT todo_list ((category+))>
<!ELEMENT items ((item*))>
<!ELEMENT category ((items))>
<!ATTLIST category
	name NMTOKEN #REQUIRED
	non CDATA #FIXED "42"
>
<!ELEMENT item ((from, to, subject, note?, state))>
<!-- Here is defined ID.-->	
<!ATTLIST item
	id ID #REQUIRED
	priority  (1 | 2 | 3 | 4 | 5) #IMPLIED
>
<!ELEMENT from ((date))>
<!ELEMENT to ((date))>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT note (#PCDATA | note_ref)*>
<!ELEMENT note_ref (#PCDATA)>
<!-- Here is defined IDREF and IDREFS.-->	
<!ATTLIST note_ref 
	%reference_attrs;
	refid IDREF #IMPLIED
	refsid IDREFS #IMPLIED
>
<!ELEMENT state EMPTY>
<!ATTLIST state
	status (undone | fleshed | done) "undone"
	must NMTOKENS #IMPLIED
>
<!ELEMENT date EMPTY>
<!ATTLIST date
	day  CDATA #REQUIRED
	month CDATA #REQUIRED
	year CDATA #REQUIRED
>

=== Soothsilver/xmlcheck/phptests/plugins/cases/DTD/Veronika Maurerova/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "data.dtd">
<!-- A7B36XML Homework  1-->
<!-- Author: Veronika Maurerova - maurever@fel.cvut.cz-->
<root-element>
	<users>
		<user id="user_1">
			<ud>
				<login>Angela</login>
				<password_hash>
				<![CDATA[
					for (i=0; i < 5; i++)
					{
						document.writeln("*****");
					}
				]]>
				</password_hash>
				<salt>SGJKD#JK76MN780</salt>
				<name>
					<first_name>Anna</first_name>
					<last_name>Nováková</last_name>
				</name>
			</ud>
			<todo_list>
				<category name="Škola">
					<items>
						<item id="item_1" priority="1">
							<from>
								<date day="01" month="03" year="2014"/>
							</from>
							<to>
								<date day="14" month="01" year="2014"/>
							</to>
							<subject>XML úkol č. 1 ></subject>
							<note>
								Zadání na stránkách předmětu XML. Souvisí s <note_ref id="ref_1" refid="									item_2">Úkolem č. 2</note_ref>.
							</note>
							<state status="undone"/>
						</item>
						<item id="item_2" priority="1">
							<from>
								<date day="01" month="03" year="2014"/>
							</from>
							<to>
								<date day="10" month="03" year="2014"/>
							</to>
							<subject><?php echo $category;?> Nastudovat přednášky 1-3 z XML.</subject>
							<note>Stáhnout a projít přednášky k vypracování úkolu.</note>
							<state status="done"/>
						</item>
						<item id="item_42" priority="1">
							<from>
								<date day="01" month="03" year="2014"/>
							</from>
							<to>
								<date day="30" month="03" year="2014"/>
							</to>
							<subject>Zajít do knihovny</subject>
							<!-- Here is used ID and IDREFS.-->	
							<note>Půjčit si knihu na XML.Souvisí s <note_ref id="ref_42" refsid="item_2 item_1">Úkolem č. 1 a 2.</note_ref>.</note>
							<state status="done"/>
						</item>
						<item id="item_3" priority="1">
							<from>
								<date day="06" month="03" year="2014"/>
							</from>
							<to>
								<date day="12" month="03" year="2014"/>
							</to>
							<subject><?php echo $category;?> PJC úkol č. 1</subject>
							<note>Zadání na webu předmětu PJC. Hotov nákres, doprogramovat.</note>
							<state status="fleshed"/>
						</item>
					</items>
				</category>
				<category name="Práce">
					<items>
						<item id="item_4" priority="1">
							<from>
								<date day="08" month="03" year="2014"/>
							</from>
							<to>
								<date day="10" month="04" year="2014"/>
							</to>
							<subject><?php echo $category;?> Studie IZO</subject>
							<note>Nalézt zdroje, načíst, vytvořit osnovu, zkonzultovat s vedením.</note>
							<state/>
						</item>
					</items>
				</category>
			</todo_list>
		</user>
		<user id="user_2">
			<ud>
				<login>Kankas</login>
				<password_hash>JKSL3K9A#IKSKS8</password_hash>
				<salt>JKSKSMLARTEPQ65</salt>
				<name>
					<first_name>Karel</first_name>
					<last_name>Slabý</last_name>
				</name>
			</ud>
			<todo_list>
				<category name="Práce">
					<items>
						<item id="item_5" priority="4">
							<from>
								<date day="20" month="12" year="2013"/>
							</from>
							<to>
								<date day="02" month="02" year="2014"/>
							</to>
							<subject><?php echo $category;?> Web KRUF</subject>
							<note>Naprogramovat kalendář akcí.</note>
							<state status="done"/>
						</item>
						<item id="item_6" priority="1">
							<from>
								<date day="03" month="03" year="2014"/>
							</from>
							<to>
								<date day="03" month="06" year="2014"/>
							</to>
							<subject><?php echo $category;?> Web Nový &amp; Starý s. r. o</subject>
							<!-- Here is used ID and IDREF.-->							
							<note>Vizitka firmy Nový s. r. o., redakční systém, informační formulář. Více v 	e-mailu. Design viz <note_ref id="ref_3" refid="item_7">úkol o grafice</note_ref>.</note>
							<state status="fleshed"/>
						</item>
						<item id="item_7" priority="1">
							<from>
								<date day="10" month="03" year="2014"/>
							</from>
							<to>
								<date day="12" month="03" year="2014"/>
							</to>
							<subject>Nový s. r. o - zavolat grafikovi</subject>
							<note>Zjistit cenu a zda už má něco hotovo. Upravit barvu pozadí na &#777;</note>
							<state/>
						</item>
					</items>
				</category>
			</todo_list>
		</user>
		<user id="user_3">
			<ud>
				<login>Silos</login>
				<password_hash>GSJ8KS8L9SK8SSJ</password_hash>
				<salt>HSJ62JSK82KS82JSO</salt>
				<name>
					<first_name>Jan</first_name>
					<last_name>Novák</last_name>
				</name>
			</ud>
			<todo_list>
				<category name="Práce">
					<items>
						<item id="item_8" priority="2">
							<from>
								<date day="02" month="04" year="2014"/>
							</from>
							<to>
								<date day="02" month="04" year="2015"/>
							</to>
							<subject><?php echo $category;?> Kniha XML</subject>
							<note>Dát dohromady a poslat na korektury</note>
							<state status="fleshed"/>
						</item>
						<item id="item_9" priority="5">
							<from>
								<date day="01" month="03" year="2014"/>
							</from>
							<to>
								<date day="01" month="04" year="2014"/>
							</to>
							<subject><?php echo $category;?> Kniha XML - obsah</subject>
							<note>
								Součástí úkolu <note_ref id="ref_4" refid="item_9"/>. Vytvořit obsah a prodiskutovat s kolegou. 
							</note>
							<state status="fleshed"/>
						</item>
					</items>
				</category>
			</todo_list>
		</user>
	</users>
</root-element>
